SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697836F02AFD9}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{652D37200671A25D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61DEC0D05F642CA8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64933DB0C949E679}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{632B552FC9BC2D8C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{632B552FC88A1D1D}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{605697836CAAD3A0}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{60C3186F9AF00BEA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{627C9145E4844787}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{62B10747441A3F3D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{630A1A7A6544E0A2}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{630A1A7A6A65CB50}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65B11D63F5516D1E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{630A1A7A55D78C44}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{621956F35DD0C82C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6328E5F6E7641841}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65092B1E3E110269}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{653B26B9CC77EAA8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{693D37E08CF99748}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F80394BBF34308}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F80394308F3C2C}" {
    }
    SCR_EntityCatalogEntry "{65F80394AE064159}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{69BD5A2C57AA309F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F80394ABEB9ACC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F80394A4A29CF2}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F80394A1F4981A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F80394A36EA63B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F803949CD64874}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F8039498C87046}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F8039495ECEAFD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65F8039496EDB166}" {
     m_bEnabled 0
    }
   }
  }
 }
}