SCR_FactionPlayerLoadout : "{6A14D10000000001}Configs/Loadouts/PAVN/Loadout_PAVN_Base.conf" {
 m_sLoadoutName "Panzerabwehrschuetze"
 m_sLoadoutResource "{1A396BE965138CBA}Prefabs/Characters/Factions/OPFOR/PAVN/PAVN_AT.et"
 m_sLoadoutImage "{64E4072188808E92}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_AT.edds"
}
