SCR_FactionPlayerLoadout : "{6A14D10000000001}Configs/Loadouts/PAVN/Loadout_PAVN_Base.conf" {
 m_sLoadoutName "Scharfschuetze"
 m_sLoadoutResource "{D319D61C81536A57}Prefabs/Characters/Factions/OPFOR/PAVN/PAVN_Sharpshooter.et"
 m_sLoadoutImage "{CA21F66986FE4498}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_Sharpshooter.edds"
}
