SCR_FactionPlayerLoadout : "{6A14D10000000001}Configs/Loadouts/PAVN/Loadout_PAVN_Base.conf" {
 m_sLoadoutName "Maschinengewehrschuetze"
 m_sLoadoutResource "{512C17FFD250A7E4}Prefabs/Characters/Factions/OPFOR/PAVN/PAVN_MG.et"
 m_sLoadoutImage "{D93455A6F79B928C}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_AR.edds"
}
