SCR_FactionPlayerLoadout : "{6A14D10000000001}Configs/Loadouts/PAVN/Loadout_PAVN_Base.conf" {
 m_sLoadoutName "Sanitaeter"
 m_sLoadoutResource "{BCF2D51C8FA333C9}Prefabs/Characters/Factions/OPFOR/PAVN/PAVN_Medic.et"
 m_sLoadoutImage "{9225D8E3CFAD7926}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_Medic.edds"
}
