SCR_XPRewardList : "{E6FC4537B53EA00B}Configs/Campaign/XPRewards.conf" {
 m_aRewardList {
  SCR_XPRewardInfo "{51BC713E81C18CF3}" {
   m_iRewardXP 25
   m_bAllowNotification 1
  }
  SCR_XPRewardInfo "{51C6A3459A34BAE8}" {
   m_iRewardXP 25
   m_bAllowNotification 1
  }
  SCR_XPRewardInfo "{552E6D601138FE41}" {
   m_iRewardXP 5
  }
  SCR_XPRewardInfo "{62B28808F905E422}" {
   m_iRewardXP 0
   m_bAllowNotification 0
  }
  SCR_XPRewardInfo "{51BC713EEC1AF2F5}" {
   m_iRewardXP 15
  }
  SCR_XPRewardInfo "{6658A2D7236CA062}" {
   m_iRewardXP -1
  }
  SCR_XPRewardInfo "{666662E1EE080C87}" {
   m_iRewardXP 5
  }
 }
}