SCR_CampaignFaction : "{ADFDBDA163950168}Configs/Factions/US_Campaign.conf" {
 m_aGroupRolePresetConfigs {
  SCR_GroupRolePresetConfig "{6A14E70000000001}" : "{792CACA432504DE4}Configs/GroupPresets/US_Vietnam/GroupPreset_USV_Assault.conf" {}
  SCR_GroupRolePresetConfig "{6A14E70000000002}" : "{C4AB528CB19641D4}Configs/GroupPresets/US_Vietnam/GroupPreset_USV_Recon.conf" {}
  SCR_GroupRolePresetConfig "{6A14E70000000003}" : "{896F6699342F4497}Configs/GroupPresets/US_Vietnam/GroupPreset_USV_MG.conf" {}
  SCR_GroupRolePresetConfig "{6A14E70000000004}" : "{2CE1AD64330E4303}Configs/GroupPresets/US_Vietnam/GroupPreset_USV_AT.conf" {}
  SCR_GroupRolePresetConfig "{6A14E70000000005}" : "{519D4E43BAB741A0}Configs/GroupPresets/US_Vietnam/GroupPreset_USV_Medic.conf" {}
 }
}
