SCR_MissionHeaderCampaign {
 World "{67C2AE120C2FD55C}world/KdK_Vietnam_v2.ent"
 m_sName "KdK Vietnam"
 m_sAuthor "EoH & KdK CaptHero"
 m_sDescription "Willkommen im Vietnam"
 m_sDetails "Original von EoH , Umbau auf HQC durch KdK CaptHero"
 m_sIcon "{F71B05F18A13692D}images/KdK_Vietnam1.edds"
 m_sLoadingScreen "{A9F32CB2359EE722}images/KdK_Vietnam2.edds"
 m_sPreviewImage "{A9F32CB2359EE722}images/KdK_Vietnam2.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_fNightTimeAcceleration 11
 m_fXpMultiplier 1.8
 m_iControlPointsCap 6
 m_bCommanderRoleEnabled 1
 m_bSpawnRandomCaches 1
}