SCR_GroupRolePresetConfig {
 m_eGroupRole ASSAULT
 m_sGroupFlagName "infantry"
 m_iGroupSize 6
 m_sGroupRoleName "#AR-GroupRole-Assault"
 m_bCanBeCreatedByPlayer 1
 m_bCanPlayerJoin 1
 m_aLoadoutResources {
  "{BE7CA93E188A5B58}Prefabs/Characters/Campaign/Final/Campaign_US_Base.et"
  "{6A14E10000000001}Prefabs/Characters/Campaign/US_Vietnam/Campaign_US_Vietnam_Rifleman.et"
  "{6A14E10000000002}Prefabs/Characters/Campaign/US_Vietnam/Campaign_US_Vietnam_AT.et"
  "{6A14E10000000003}Prefabs/Characters/Campaign/US_Vietnam/Campaign_US_Vietnam_Medic.et"
  "{6A14E10000000004}Prefabs/Characters/Campaign/US_Vietnam/Campaign_US_Vietnam_MG.et"
  "{6A14E10000000005}Prefabs/Characters/Campaign/US_Vietnam/Campaign_US_Vietnam_Sharpshooter.et"
 }
}
