SCR_GroupRolePresetConfig {
 m_eGroupRole ASSAULT
 m_sGroupFlagName "infantry"
 m_iGroupSize 6
 m_eRequiredRank PRIVATE
 m_bCanBeCreatedByPlayer 1
 m_bCanPlayerJoin 1
 m_sGroupRoleName "#AR-GroupRole-Assault"
 m_aLoadoutResources {
 "{918C557BF3506286}Prefabs/Characters/Campaign/Final/Campaign_USSR_Base.et"
 "{3413922BA28A9FFD}Prefabs/Characters/Factions/OPFOR/PAVN/PAVN_Rifleman.et"
  "{1A396BE965138CBA}Prefabs/Characters/Factions/OPFOR/PAVN/PAVN_AT.et"
  "{BCF2D51C8FA333C9}Prefabs/Characters/Factions/OPFOR/PAVN/PAVN_Medic.et"
  "{512C17FFD250A7E4}Prefabs/Characters/Factions/OPFOR/PAVN/PAVN_MG.et"
  "{D319D61C81536A57}Prefabs/Characters/Factions/OPFOR/PAVN/PAVN_Sharpshooter.et"
 }
}
